Создание массива

In [1]:
import numpy as np
import pandas as pd

In [5]:
#Массив в Python задаётся с помощью функции array() модуля NumPy,
# которая трансформирует вложенные в неё последовательности в массив. 
# Простой способ задать массив — перечислить его элементы внутри квадратных скобок [] через запятую: 
arr1 = np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
arr2 = np.array([5,6,7,8], dtype = float)
arr2.dtype

dtype('float64')

In [7]:
# Для создания массивов большей размерности каждая строка должна быть помещаться в квадратные скобки, 
# при этом строки разделяются запятой. 
# Для двумерного массива (матрицы) можно использовать такой код:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# Узнать размерность массива можно с помощью функции shape():
np.shape(arr3)

(3, 3)

Массив из Pandas

В процессе анализа данных возникают ситуации, когда требуется выполнить с данными, хранящимися в Pandas DataFrame, сложные математические операции. Мы можем преобразовать датафрейм или его часть, содержащую количественные показатели, в объект ndarray с помошью функции values библиотеки Pandas:

In [2]:
import numpy as np
import pandas as pd

df = pd.DataFrame()
x = df.values
type(x)

numpy.ndarray

Используя функцию values, массив можно получить из Series:

In [18]:
import numpy as np
import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series.values
# np.shape(my_series)
my_series

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

Другие способы создания массива
Иногда при решении задач нужно создать массив заданной структуры до того, как становится известно о хранящихся в нём данных. В NumPy есть функции, которые позволяют задавать размерность массива, выделять память для его хранения и заполнять массив элементами (единицами, нулями).



In [ ]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

In [18]:
np.random.randint(0, 10, (3, 3))

array([[4, 7, 2],
       [4, 1, 2],
       [0, 5, 8]])

Примерчики 
np.array([[8,13,18,4], [25,3,18,28], [14,15,18,24], [1,2,3,4]]) 
Какие элементы расположены на главной диагонали массива, заданного с помощью кода выше?
8, 3, 18, 4 верно
18, 18, 18, 1
25, 3, 18, 24
4, 28, 24, 4
этот массив не имеет главной диагонали

In [19]:
np.array([[8,13,18,4], [25,3,18,28], [14,15,18,24], [1,2,3,4]]) 

array([[ 8, 13, 18,  4],
       [25,  3, 18, 28],
       [14, 15, 18, 24],
       [ 1,  2,  3,  4]])

my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])
Какие элементы расположены в последнем столбце массива, заданного с помощью кода выше?
301, 150.5, 201
301.0, 150.5, 201.0
-99.0, 0.5, 1.0
281.0, 140.5, 181.0 верно
нет правильного ответа

In [21]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

С помощью каких вариантов кода можно создать массив, среднее арифметическое всех элементов главной диагонали которого равно 1?
np.ones(5)
np.ones(5,5)
np.ones((5,5))
np.eye(5)
np.full((5,5), 1)
np.array([[1,2,3,4,5], [5,1,2,3,4], [4,5,1,2,3], [3,4,5,1,2], [2,3,4,5,1]])

In [22]:
np.array([[1,2,3,4,5], [5,1,2,3,4], [4,5,1,2,3], [3,4,5,1,2], [2,3,4,5,1]])

array([[1, 2, 3, 4, 5],
       [5, 1, 2, 3, 4],
       [4, 5, 1, 2, 3],
       [3, 4, 5, 1, 2],
       [2, 3, 4, 5, 1]])

[[1, 1, 1],
 [0, 2, 2],
 [2, 4, 1]]
 С помощью каких вариантов кода НЕВОЗМОЖНО создать массив, представленный в примере выше?
np.random.randint(0, 4, (3, 3))
np.random.randint(0, 5, (3, 3))
np.random.randint(0, 6, (3, 3))
np.random.randint(0, 5, 3)

In [54]:
np.random.randint(0, 5, 3),np.random.randint(0, 4, (3, 3))

(array([4, 1, 0]),
 array([[1, 0, 1],
        [3, 2, 0],
        [0, 2, 2]]))

Какие из представленных вариантов кода можно использовать для создания массива 4х4, полностью заполненного единицами?
np.array([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]])
np.eye(4)
np.ones((4, 4), dtype=float)
np.full((4, 4), 1)

In [ ]:
np.array([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]), np.ones((4, 4), dtype=float), np.full((4, 4), 1)

Какие из вариантов кода можно использовать для создания массива, заполненного нечётными числами?
np.array(range(9))
np.ones((2,2,2))
np.array([i for i in range(11) if i%2])
np.arange(1, 14, 2)

In [58]:
np.ones((2,2,2)),np.array([i for i in range(11) if i%2]),np.arange(1, 14, 2)

(array([[[1., 1.],
         [1., 1.]],
 
        [[1., 1.],
         [1., 1.]]]),
 array([1, 3, 5, 7, 9]),
 array([ 1,  3,  5,  7,  9, 11, 13]))