In [18]:
import numpy as np
import pandas as pd
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
np.shape(big_secret)

(5, 51)

In [ ]:
#9.3.1

In [40]:
round(big_secret[:,50].sum(),2)

3154.33

In [52]:
sum(np.diagonal(big_secret[:,:5]))

121.37188663699624

In [54]:
np.diagonal(big_secret[:,:5]).sum().round(2)

121.37

In [45]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array,my_array[:,2]


(array([[ 1,  2,  3,  4],
        [10, 11, 12, 13],
        [45, 46, 47, 48]]),
 array([ 3, 12, 47]))

np.prod произведение элементов
np.diagonal диагональ элементов

In [70]:
np.prod(np.diagonal(big_secret [:, -5:]))

341505315559.2347

In [71]:
big_secret_sm = big_secret[:,-5:]
p=1
for i in range(len(big_secret_sm)):
    p *= big_secret_sm[i][i]
p

341505315559.2347

In [74]:
my_array = np.random.randint(1, 100, (4, 6)) 
my_array

array([[12, 90, 25,  8, 42, 48],
       [87, 19, 60, 35, 44, 57],
       [75, 68, 61, 94, 45, 40],
       [68, 52, 60, 55, 76, 79]])

In [77]:
my_slice = my_array[1:3, 2:4]
my_slice[:]=0

In [78]:
my_array

array([[12, 90, 25,  8, 42, 48],
       [87, 19,  0,  0, 44, 57],
       [75, 68,  0,  0, 45, 40],
       [68, 52, 60, 55, 76, 79]])

In [82]:
my_slice1 = big_secret[0::2,0::2]
my_slice2 = big_secret[1::2,1::2]
my_slice2
my_slice1[:] = 1
my_slice2[:] = -1
big_secret
sum(np.diagonal(big_secret [:, :5]))


1.0

In [87]:
big_secret[0::2,0::2]=-1
big_secret[1::2, 1::2]=1
big_secret
# np.diagonal(big_secret [:, :5]).sum()
np.prod(np.diagonal(big_secret [:, -5:]))

-1.0