Операции с массивами
Особенностью работы с массивами в NumPy является то, что возможности библиотеки позволяют выполнять любые математические действия с массивами без использования циклов for, благодаря чему вычисления производятся с большой скоростью. В NumPy над массивами можно производить все стандартные арифметические операции.

Операции выполняются поэлементно, поэтому для получения корректного результата размерность массивов должна быть одинаковой. Также можно производить математические операции между массивом и числом.

У нас есть два массива: найдём их сумму, разность, произведение, частное и умножим один из массивов на число:

In [1]:
import numpy as  np
import pandas as  pd

In [2]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = a-b
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format
      (result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [-9 -9 -9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


Универсальные функции
Универсальными называют функции, которые выполняют поэлементные операции над данными, хранящимися в объектах ndarray.  Большинство универсальных функций относятся к унарным операциям и выполняются над каждым элементом массива по очереди. Унарные операции — это  и есть операции, которые выполняются над каждым элементом массива по очереди.

Рассмотрим список часто используемых универсальных функций NumPy. При вызове каждой из этих функций необходимо указывать название библиотеки NumPy: np.isnan(имя_массива):

Функция	Описание
abs -	Абсолютное значение целых, вещественных или комплексных элементов массива
sqrt - вадратный корень каждого элемента массива
exp - Экспонента (ex) каждого элемента массива
log, log10, log2, log1p	- Натуральный (по основанию е), десятичный, двоичный логарифм и функция log(1+x) соответственно
modf -	Дробные и целые части массива в виде отдельных массивов
isnan -	Массив логических (булевых) значений, показывающий, какие из элементов исходного массива  являются NaN (не числами)
cos, sin, tan - Обычные тригонометрические функции
arccos, arcsin, arctan - Обратные тригонометрические функции

Изменение размерности массива
В некоторых задачах машинного обучения для подготовки данных к обработке нужно изменить исходную форму массива, например, преобразовать многомерный массив в одномерный, поменять местами строки и столбцы.

Замена местами строк и столбцов двумерного массива называется транспонированием. Для выполнения этой операции в NumPy используется метод T:

In [3]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

Для превращения массива одной размерности в массив другой — обычно для преобразования одномерного массива в многомерный — используется метод reshape. Изменить размерность массива можно только в том случае, если число элементов в исходном и в целевом массиве совпадает:

In [4]:
my_array = np.random.randint(0, 10, 20)
my_array.reshape((4,5))

array([[1, 0, 7, 9, 3],
       [3, 1, 1, 6, 7],
       [6, 4, 3, 1, 4],
       [3, 2, 4, 6, 0]])

Для преобразования многомерного массива в одномерный используется метод flatten:

In [5]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
my_array.flatten()

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

Сравнения и маски
Научимся сравнивать элементы массива с числом и извлекать из него только те элементы, которые больше или меньше заданного числа. Для этого создадим массив размера 3х4, произвольно заполненный числами от 0 до 10. При создании массива используется генератор случайных чисел, так что у вас могут получиться другие значения:

In [6]:
my_array = np.random.randint(0, 10, (3,4))

Теперь посмотрим, какие из элементов меньше 5:

In [7]:
my_array<5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [ True, False, False, False]])

Мы получили новый массив, заполненный значениями True/False в зависимости от того, меньше или больше пяти элемент, находящийся на соответствующей позиции в исходном массиве. Для того, чтобы получить элементы массива my_array, которые меньше пяти, воспользуемся кодом ниже. Отобранные элементы представляют собой одномерный массив.

In [8]:
my_array[my_array<5]

array([4, 2, 4, 1, 0])

Маска нужна для выбора только определенных строк или столбцов из всего массива и скрытия остальных. Маска в Python задаётся при помощи булевых 0 и 1, где 0 скрывает столбец или строку, а 1 оставляет ее на виду. Выведем первый и третрий столбец массива:

In [9]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[4, 4],
       [5, 5],
       [0, 7]])

Сортировка двумерных массивов
В двумерных массивах можно выполнять сортировку элементов строк и столбцов:

Сортировка выполняется с помощью функции sort, в качестве параметров функция получает сам массив, а также номер оси (0 (для столбцов) или 1 (для строк)) , элементы которой необходимо отсортировать. 

Как можно отсортировать элементы строк и столбцов?

Отсортируем элементы строк:

In [48]:
my_array = np.random.randint(0, 10, (4, 6))
my_array
# np.sort(my_array, axis=1)
# np.sort(my_array, axis=0)

array([[1, 5, 7, 2, 4, 1],
       [8, 9, 8, 7, 0, 1],
       [3, 9, 2, 5, 2, 2],
       [7, 7, 5, 9, 0, 9]])

In [49]:
np.sort(my_array, axis=1),np.sort(my_array, axis=0)

(array([[1, 1, 2, 4, 5, 7],
        [0, 1, 7, 8, 8, 9],
        [2, 2, 2, 3, 5, 9],
        [0, 5, 7, 7, 9, 9]]),
 array([[1, 5, 2, 2, 0, 1],
        [3, 7, 5, 5, 0, 1],
        [7, 9, 7, 7, 2, 2],
        [8, 9, 8, 9, 4, 9]]))

Упражнения
Для выполнения упражнений из следующего блока мы будем использовать массив, созданный с помощью кода:

In [70]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

Задание 2
Чему равна сумма косинусов элементов первой строки массива great_secret? Ответ округлите до двух знаков после запятой.

In [77]:
round(sum([np.cos(x) for i in great_secret[:1] for x in i]),2)

0.16

In [78]:
sum(great_secret[great_secret>50])

5470.0

In [80]:
great_secret.flatten()[150]

7.0710678118654755

In [81]:
round(sum(np.sort(great_secret, axis=0)[-1]), 2)

115.12