Математические и статистические операции
Модуль NumPy содержит множество базовых статистических функций, которые помогают описать имеющиеся данные: среднее арифметическое (mean), медиана (median), стандартное отклонение (std), корреляция (corrcoef) и прочие. Давайте посмотрим, как они работают. 

Для изучения функций будем использовать набор данных, содержащих информацию об учениках шестого класса. Данные об учениках представлены в таблице:

ID 	Рост,см	Масса кг Cредний балл
1	135	       34	    4
2	160	       43     	5
3	163	       40    	4.3
4	147	       44    	5
5	138	       41    	4.7
6	149	       54   	3.9
7	136	       39	    4.2
8	154	       48   	4.9
9	137	       35   	3.7
10	165	       60    	4.6
Создайте массив, содержащий эти данные, и сохраните его под именем students.

In [3]:
import numpy as np

In [4]:
a = np.array([1,135,34,4,2,160,43,5,3,163,40,4.3,4,147,44,5,5,138,41,4.7,6,149,54,3.9,7,136,39,4.2,8,154,48,4.9,9,137,35,3.7,10,165,60,4.6])
students = a.reshape(10,4)
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

Средние величины
Среднее арифметическое (mean) — сумма всех значений, делённая на их количество, показывает общую тенденцию данных и описывает их одним числом. Узнаем среднюю успеваемость школьников в классе, используя функцию mean:

In [62]:
mean = np.mean(students[:,-1])
mean1 = np.mean(students[:,-1:])
mean1



4.430000000000001

In [64]:
students[:,-1], students[:,-1:]

(array([4. , 5. , 4.3, 5. , 4.7, 3.9, 4.2, 4.9, 3.7, 4.6]),
 array([[4. ],
        [5. ],
        [4.3],
        [5. ],
        [4.7],
        [3.9],
        [4.2],
        [4.9],
        [3.7],
        [4.6]]))

In [99]:
students=np.array([[1,2,3], [5,6,7], [9,10,11]])
# students[:,:],students[:,:-1],students[:,-1:],students[:,-1]
students[:,1:2],

(array([[ 2],
        [ 6],
        [10]]),)

Медиана — это такое число, что ровно половина элементов из выборки больше него, а другая половина меньше него. Если в выборке есть выбросы (значения, которые принимают величину существенно выше или ниже среднего и выделяются из всей выборки), то медиана будет лучше характеризовать всю выборку, чем среднее арифметическое.

Узнаем, как учится средний ученик, с помощью функции median:

In [94]:
median = np.median(students[:,-2])
median

42.0

In [7]:
median = np.median(students[:,-1:],axis=0)
median
type(median)

numpy.ndarray

In [6]:
median1 = np.median(students[:,-1])
median1
type(median1)

numpy.float64

Полученные результаты говорят нам о том, что в среднем школьники учатся хорошо, среди них много отличников (медианное значение среднего балла выше среднего арифметического). Заметим, что школьников в выборке всего 10, а медиана — это значение выборки, при котором ровно половина значений меньше неё, а половина — больше. 

Python сначала упорядочит значения по возрастанию, а затем возьмет среднее средних элементов полученного ряда, то есть пятого и шестого. Проверим это, используя функцию sort для сортировки значений оценок:



In [6]:
sort = np.sort(students[:,-1])
sort1 = np.sort(students[:,-1:], axis=0)

(sort1[4]+sort1[5])/2, (sort[4]+sort[5])/2


(array([4.45]), 4.449999999999999)

In [79]:
sort1, sort

(array([[3.7],
        [3.9],
        [4. ],
        [4.2],
        [4.3],
        [4.6],
        [4.7],
        [4.9],
        [5. ],
        [5. ]]),
 array([3.7, 3.9, 4. , 4.2, 4.3, 4.6, 4.7, 4.9, 5. , 5. ]))

In [102]:
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

Задание 1:Чему равно медианное значение массы тела школьников?

In [108]:
np.median(students[:,2:3])

42.0

In [109]:
np.median(students[:,-2])

42.0

Задание 2:На сколько среднее арифметическое массы тела школьников больше медианного значения для этого же показателя? Дайте ответ в килограммах с точностью до одной десятой кг.

In [112]:
medmean=np.mean(students[:,-2])-np.median(students[:,-2])
medmean

1.7999999999999972

Коэффициент корреляции
Корреляция — статистическая взаимосвязь случайных величин. Мерой корреляции служит одноименный коэффициент, который показывает, насколько сильно связаны величины, он может быть положительным или отрицательным, а по модулю принимает значение от 0 до 1. Отрицательный коэффициент говорит о том, что случайные величины связаны, но при увеличении одной из них вторая уменьшается. Если коэффициент положительный, то величины изменяются в одном направлении.

Аналитики часто оперируют в своей работе данной величиной и ошибаются, делая ложные выводы о данных. Связано это с тем, что не всегда наличие корреляции между двумя показателями говорит о том, что между ними есть причинно-следственная связь.

Давайте узнаем, как связан рост и вес наших школьников, посчитав коэффициент корреляции столбцов матрицы:

In [113]:
corr = np.corrcoef(students[:,1], students[:,2])
corr


array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

между ростом и успеваемостью

In [114]:
corr = np.corrcoef(students[:,1], students[:,-1])
corr

array([[1.        , 0.46293714],
       [0.46293714, 1.        ]])

между массой тела и успеваемостью

In [115]:
corr = np.corrcoef(students[:,2], students[:,-1])
corr

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [116]:
std = np.std(students[:,1])
std

11.083320801997928

Задание 4
Используя имеющийся набор данных о школьниках, найдите, чему равно стандартное отклонение их средних баллов.

In [117]:
std = np.std(students[:,-1])
std

0.4517742799230607

функция Дисперсии

In [119]:
var = np.var(students[:,2])
var

60.36